### ISSUE TITLE
[feature request] Allow side scroll to be able to add even more tools. Like CRM, Data , IoT, Hardware, Production.

### ISSUE THREAD

**Issue by cocoonkid** [Wivik/devops-solutions-map#20]
[feature request] Allow side scroll to be able to add even more tools. Like CRM, Data , IoT, Hardware, Production.

I really like this tool! Thanks so much for your consideration!

#7 would then be a "requirement" though.

**Comment by Wivik** [comment]
Hello,

Thanks for submitting this feature request. 

I'm not sure to understand the request, you can add whichever tool and use case you want in the tiles. Can you explain a little more please ?

**Comment by cocoonkid** [comment]
Thanks for taking the time to reply.

I wonder if I add 70 tools will the space suffice?

Ideally, I suppose right now, the tool would allow to scroll sideways and the remaining items will appear nicely.

My apology if my explanation is still not sufficient. If it is not I'd get back to you with a mockup image asap.

**Comment by Wivik** [comment]
Ah I think I understand. Actually there is no display limitation since the HTML template and the CSS are quite simple (I'm not a CSS warrior, so I've kept it simple). Stacking the tiles and the tools inside them will just expand the vertical scrolling.

On an IRL implementation I have the "Programming Languages" tile that got quite long when expanded since there's a lot of entries but that wasn't too problematic. However opening all box can become a little messy I admit. I think there's place for improvement in the design.

If you test on a reduced screen size such as smartphones (you can do it with the browser's dev tools), you'll see the horizontal scrolling working fine, and the swimlanes stacking 

![Peek 2023-05-29 16-45](https://github.com/Wivik/devops-solutions-map/assets/48727868/22010a86-8c5d-41a2-9f81-f22115274427)

I can't say the design is responsive since nothing has been done for that, but this current state seems to work fine :sweat_smile: 

So short answer : yes you can add dozen of tools, the space will just extend and you'll have to scroll more since the render is a basic HTML page.

**Comment by cocoonkid** [comment]
Awesome! Apology for asking at all. :) 

Thanks for taking the time to respond in detail! 

Have a great day ahead!

**Comment by Wivik** [comment]
No worries, any feedback that could improve the tool remains appreciated !
