### ISSUE TITLE
Can this generate a static site?

### ISSUE THREAD

**Issue by NickLarsenNZ** [Wivik/devops-solutions-map#3]
I think it would be useful to optionally produce the static output so that it doesn't have to be hosted.

An example being a github page.

**Comment by Wivik** [comment]
First result available in [the following branch feat/static-website ](https://github.com/Wivik/devops-solutions-map/tree/feat/static-website) .

Published on GitHub Pages for testing : https://wivik.github.io/devops-solutions-map/

So far it looks good. There is an issue with the "Open All" button that doesn't work since its action was managed by Flask.

Two ways to generate : 

1. With the code directly

```bash
python app.py --freeze [--freezer-base-url http://mywebsite/folder]
```

Base URL arg is required in case the website in not at the root of the domain, GitHub Pages typically. If not, the argument is not necessary. It can be verified using Python's builtin web server : 

```bash
cd build
python -m http.server 8080
```
Then go to http://localhost:8080 

2. Using the container image, it's a kind of dirty for now because I've had some permissions issues

```bash
mkdir build
chmod 777 build # :vomiting_face: 
podman run --rm -v ./build:/devops-map/build:Z ghcr.io/wivik...... --freeze
```

I still have to update the documentation and ensure I've not broken anything, but so far so good :+1:
